services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH=true
    depends_on:
      - mongo
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"


  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis

  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=redis
      - MINIO_ROOT_PASSWORD=redis
      - MINIO_DEFAULT_BUCKETS=redis_bucker
    restart: always

volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local