'use strict';

/*
 * Name: provide-traceid
 * Descrip: Custom plugin to inject as traceId header.
 *      Uses the correlationId as generated by the microgateway for every request.
 *      This same correlationId is used as the "i=" parameter to identify each entry in the logger routine.
 *
 *
 * Config stanza:
 *  activate: Toggle provide-traceid functionality
 *    example: true
 *
 *  prefix
 *  4-digit prefix to the correlationId
 *  Example: "emg-"   
 *
 */


module.exports.init = function(config, logger, stats) {

	//== Initialisation (for each worker thread started )
  var plugId = "-- PT: ";
	var idMsg = plugId + ' Provide-TraceId';
	
	var idPrefix;
	if (config.activate) {
		idMsg += " initialised and active";
		idPrefix = config.prefix ? config.prefix : "emg-";
		idMsg += ". prefix is " + idPrefix;
	} else {
		idMsg += ' present but inactive.';
	}
	console.log(idMsg);
	
	//== On traffic ...
	return {
	  
		onrequest: function(req, res, next) {

			if (config.activate) {
				try {
					req.headers['traceId'] = idPrefix + req.correlationId;
				} catch (e) {}					
			}

			//== Traffic must flow to next (plugin)
			next();

		}
	
	};

}
