apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: deepSheekChat
spec:
  selector:
    matchLabels:
      app: deepSheekChat
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: deepSheekChat
    spec:
      containers:
        - name: deepSheekChat
          image: springboot-k8s-example:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191 # The port that the container is running on in the cluster