# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CommonConnector

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  checkout-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checking out git
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: packaging in maven
        run: mvn clean package -DskipTests=true
      - name: integration testing
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp mtnNotificationGenerator/target/*.jar staging && cp mtnCommonBean/target/*.jar staging && cp mtnConnectorTemplate/target/*.jar staging && cp mtnConnectorSalary/target/*.jar staging && cp mtnConnectorUserProfile/target/*.jar staging && cp mtnvalidationConnector/target/*.jar staging && cp mtnLoyaltyManagementConnector/target/*.jar staging && cp mtnBatchProcessing/target/*.jar staging && cp mtnNotificationGenerator/target/*.jar staging && cp mtnUrlShortener/target/*.jar staging
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: commonConnector
            path: staging
      - name: set sonar cube
        run: echo "does not have sonar cube access project create access"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push commonBean
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          file: DockerfileBean
          tags: indranil13/commonconnector:mtnCommonBean${{secrets.RELEASE_VERSION}}.${{ github.run_number }}
      - name: Build and push commontemplate
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          file: DockerfileTemplate
          tags: indranil13/commonconnector:mtnConnectorTemplate${{secrets.RELEASE_VERSION}}.${{ github.run_number }}
      - name: Build and push userProfile
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          file: DockerfileUserProfile
          tags: indranil13/commonconnector:mtnConnectorUserProfile${{secrets.RELEASE_VERSION}}.${{ github.run_number }}



    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
